/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioIdRouteImport } from './routes/studio.$id'
import { Route as StudioTplIdRouteImport } from './routes/studio.tpl.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioIdRoute = StudioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioRoute,
} as any)
const StudioTplIdRoute = StudioTplIdRouteImport.update({
  id: '/tpl/$id',
  path: '/tpl/$id',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$id': typeof StudioIdRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/tpl/$id': typeof StudioTplIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio/$id': typeof StudioIdRoute
  '/studio': typeof StudioIndexRoute
  '/studio/tpl/$id': typeof StudioTplIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$id': typeof StudioIdRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/tpl/$id': typeof StudioTplIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/studio' | '/studio/$id' | '/studio/' | '/studio/tpl/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studio/$id' | '/studio' | '/studio/tpl/$id'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/studio/$id'
    | '/studio/'
    | '/studio/tpl/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$id': {
      id: '/studio/$id'
      path: '/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof StudioIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/tpl/$id': {
      id: '/studio/tpl/$id'
      path: '/tpl/$id'
      fullPath: '/studio/tpl/$id'
      preLoaderRoute: typeof StudioTplIdRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface StudioRouteChildren {
  StudioIdRoute: typeof StudioIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioTplIdRoute: typeof StudioTplIdRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioIdRoute: StudioIdRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioTplIdRoute: StudioTplIdRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
